# Generated by Django 5.1.4 on 2025-05-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
